# To install the git pre-commit hook run:
#   pre-commit install
# To update the pre-commit hooks run:
#   pre-commit install-hooks
exclude: ^(\.tox|\.bumpversion\.cfg)(/|$)
default_stages: [pre-commit, pre-merge-commit, pre-push]
repos:
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.19.1
  hooks:
  - id: gitlint
    stages: [commit-msg]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-yaml
  - id: debug-statements
  - id: detect-private-key
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  - id: trailing-whitespace
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.11.2
  hooks:
  - id: ruff
# - repo: https://github.com/PyCQA/docformatter
#   rev: v1.7.1
#   hooks:
#   - id: docformatter
#     args: [--in-place, --wrap-summaries, '95', --config, ./pyproject.toml]
- repo: https://github.com/myint/rstcheck
  rev: v6.2.4
  hooks:
  - id: rstcheck
    args: [--report-level=warning, '--ignore-directives=automodule,testsetup']
    additional_dependencies: [sphinx]
    exclude: ^(ci/templates/README.rst)(/|$)
- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
  - id: black
    args: [--skip-string-normalization, --line-length=79]
- repo: https://github.com/asottile/blacken-docs
  rev: 1.19.1
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==23.3.0]
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.5.0
  hooks:
  - id: detect-secrets
          # args: [--baseline, ci/secrets.baseline]
